### ISSUE TITLE
Meta Upscale Module

### ISSUE THREAD

**Issue by Auth0rM0rgan** [XuecaiHu/Meta-SR-Pytorch#28]
Hey @XuecaiHu, 

Nice work and thanks for sharing your code. I have a question about your meta upscale module. 
1) What is the difference between the upscale module in meta.py and metardn.py? 

Thanks!

**Comment by tetterl** [comment]
`metardn.py` implements Meta-RDN from the paper. I'm not fully sure if `meta.py` implements BicuConv or Meta-Bicu from the paper. Maybe @XuecaiHu can clarify it?

**Comment by XuecaiHu** [comment]
@Auth0rM0rgan  @tetterl  sorry for the late reply.  meta.py is not the meta-bicu/ bicuconv.  In  meta.py, we directly  concatenate the output feature(by upsampling s times) and pos_mat  instead of using the pos_mat to predict weights for each pixel. But we find it doesnot work.  It is a methods we donot mention in our paper.

**Comment by XuecaiHu** [comment]
We donot  provide  the implementation  of metabicu and bicuconv.  It is easy to implement them by reference to meta.py

**Comment by tetterl** [comment]
`meta.py` has a bug on line https://github.com/XuecaiHu/Meta-SR-Pytorch/blob/master/model/meta.py#L99 since we always feed the scaling factor of 2. That might be the reason that it doesn't work.

**Comment by XuecaiHu** [comment]
thank you, i will fixed the bug later and retrain our model.
