### ISSUE TITLE
Does the scale over 4x work?

### ISSUE THREAD

**Issue by jason71995** [XuecaiHu/Meta-SR-Pytorch#32]
Hi @XuecaiHu ,

As same as the title, I have few question about this paper.
According to the paper, I think any scale factor could work on Meta-SR, 
like 8x, 16x or 16.5x, is it right? 

If the scale factor over 4x worked, 
have you experiment the performance on 8x or 16x? if not, why?

**Comment by XuecaiHu** [comment]
the test scale factor can be any  value. But since our model is trained on datasets whoes scale factor is sampled from 1 to 4,   thus we  donot show the performance on 8x or 16x (bigger than 4x).  

However, the trained model still can test on 8x or 16x (bigger than 4x).  My experiences tell me that  
the performance is  lower than that of the model trained on single scale factor (8x or 16x). 
If you want to use the model for application where the scale factor s is bigger than 4x, i think it is better to  retrain the model and scale factor is sampled from 1 or  s ( s is the max scale factor).  And you will get better results.   Donot test the scale factor which is out of the traing scale factors range. any scale factor in the range of traing scale factors is ok.

In this paper, we mainly show the capacity of our model to solve non-integer scale factor and single model for any scale factor.  And most SISR models only  study the scale factor 2,3,4. That is why we donot test on 8x, 16x.  That is the reason.

**Comment by jason71995** [comment]
Thanks for your reply.

By the way, Meta-SR is amazing works on super resolution!
